# Generated by Django 4.1.4 on 2023-03-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_app', '0003_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bonus',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=10000000),
        ),
    ]
