# Generated by Django 4.1.4 on 2023-04-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_app', '0005_users_mail_users_nambers'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='adress',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
