# Generated by Django 4.1.4 on 2023-04-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_app', '0006_call_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='adress',
        ),
        migrations.AddField(
            model_name='users',
            name='adress',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
